// Secret-key file management + AES-256-GCM helpers.
// The key lives at $SITE_ROOT/data/secret.key (32 random bytes, mode 0600).
// Generated by `site-admin init` if absent; never rotated automatically.
//
// Used to encrypt OAuth tokens at rest (spec §17). Stored ciphertext layout:
//   [12-byte IV][16-byte auth tag][N-byte ciphertext]   = total N + 28 bytes.

import crypto from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';

const KEY_LENGTH = 32;
const IV_LENGTH = 12;
const TAG_LENGTH = 16;
const ALGO = 'aes-256-gcm' as const;

export function secretKeyPath(siteRoot: string): string {
  return path.join(siteRoot, 'data', 'secret.key');
}

/**
 * Ensure $SITE_ROOT/data/secret.key exists. Generates 32 random bytes and
 * writes them with mode 0600 if absent. Idempotent.
 *
 * @returns true if a new key was generated, false if it already existed.
 */
export function ensureSecretKey(siteRoot: string): boolean {
  const file = secretKeyPath(siteRoot);
  if (fs.existsSync(file)) return false;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, crypto.randomBytes(KEY_LENGTH), { mode: 0o600 });
  return true;
}

export function readSecretKey(siteRoot: string): Buffer {
  const file = secretKeyPath(siteRoot);
  const buf = fs.readFileSync(file);
  if (buf.length !== KEY_LENGTH) {
    throw new Error(
      `secret.key must be exactly ${KEY_LENGTH} bytes; got ${buf.length} from ${file}`
    );
  }
  return buf;
}

/** Encrypt a UTF-8 string. Returns a Buffer suitable for storing in a BLOB column. */
export function encrypt(plaintext: string, key: Buffer): Buffer {
  const iv = crypto.randomBytes(IV_LENGTH);
  const cipher = crypto.createCipheriv(ALGO, key, iv);
  const ct = Buffer.concat([cipher.update(plaintext, 'utf8'), cipher.final()]);
  const tag = cipher.getAuthTag();
  return Buffer.concat([iv, tag, ct]);
}

/** Decrypt a Buffer produced by `encrypt`. Throws on auth-tag mismatch. */
export function decrypt(blob: Buffer, key: Buffer): string {
  if (blob.length < IV_LENGTH + TAG_LENGTH) {
    throw new Error(`ciphertext too short (got ${blob.length} bytes)`);
  }
  const iv = blob.subarray(0, IV_LENGTH);
  const tag = blob.subarray(IV_LENGTH, IV_LENGTH + TAG_LENGTH);
  const ct = blob.subarray(IV_LENGTH + TAG_LENGTH);
  const decipher = crypto.createDecipheriv(ALGO, key, iv);
  decipher.setAuthTag(tag);
  return Buffer.concat([decipher.update(ct), decipher.final()]).toString('utf8');
}
