#!/bin/bash
# Overwrite the generated Apache vhost with an rkr-blog-specific config.
#
# Key differences from the stock proxy template:
#   - DocumentRoot /var/www/rkr-blog so %{DOCUMENT_ROOT} resolves for the
#     cache fast-path rewrite check
#   - RewriteRule serves cached image derivatives directly from disk when
#     present, bypassing Fastify entirely
#   - immutable Cache-Control on /cache/ and /static/ (content-hashed URLs)
set -euo pipefail

: "${TMP_DIR:?TMP_DIR not set}"
: "${APP_NAME:?APP_NAME not set}"
: "${DOMAIN_NAME:?DOMAIN_NAME not set}"
: "${FASTIFY_APP_PORT:?FASTIFY_APP_PORT not set}"
: "${FASTIFY_APP_DATA_PATH:?FASTIFY_APP_DATA_PATH not set}"

DATA_DIR="${FASTIFY_APP_DATA_PATH}/${APP_NAME}"   # e.g. /var/www/rkr-blog
PORT="${FASTIFY_APP_PORT}"

cat > "${TMP_DIR}/${APP_NAME}.conf" << EOF
# Apache vhost for ${APP_NAME} — generated by deploy/hooks/apache.build.post.sh
# Required modules: rewrite proxy proxy_http headers

<VirtualHost *:80>
    ServerName ${DOMAIN_NAME}

    # Preserve ACME challenge directory for Let's Encrypt renewal
    Alias /.well-known ${DATA_DIR}/.well-known
    <Directory ${DATA_DIR}/.well-known>
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well-known
    RewriteRule ^(.*)$ https://%{HTTP_HOST}\$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${DOMAIN_NAME}

    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem

    ErrorLog  /var/log/apache2/${APP_NAME}_error.log
    CustomLog /var/log/apache2/${APP_NAME}_access.log combined

    # DocumentRoot is needed so %{DOCUMENT_ROOT} resolves in the RewriteCond
    # below.  The directory itself is never listed (Options -Indexes).
    DocumentRoot ${DATA_DIR}
    <Directory ${DATA_DIR}>
        Options -Indexes
        Require all granted
    </Directory>

    RewriteEngine On

    # Fast-path: serve cached image derivatives directly from disk.
    # URI:  /img/<id>.<ophash>.<format>
    # Disk: ${DATA_DIR}/cache/img/<id>.<ophash>.<format>
    # Falls through to ProxyPass on cache miss.
    RewriteCond %{DOCUMENT_ROOT}/cache%{REQUEST_URI} -f
    RewriteRule ^/img/(.*)$ /cache/img/\$1 [L]

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS
    ProxyPass        / http://127.0.0.1:${PORT}/ enablereuse=on
    ProxyPassReverse / http://127.0.0.1:${PORT}/

    # Long-lived immutable cache for content-hashed URLs
    <LocationMatch "^/(cache|static)/">
        Header set Cache-Control "public, max-age=31536000, immutable"
    </LocationMatch>
</VirtualHost>
EOF

echo "  apache.build.post: custom rkr-blog vhost written"
