#!/bin/bash
# Overwrite the generated Apache vhost with an rkr-blog-specific config.
#
# Key differences from the stock proxy template:
#   - DocumentRoot /var/www/rkr-blog so %{DOCUMENT_ROOT} resolves for the
#     cache fast-path rewrite check
#   - RewriteRule serves cached image derivatives directly from disk when
#     present, bypassing Fastify entirely
#   - immutable Cache-Control on /cache/ and /static/ (content-hashed URLs)
set -euo pipefail

: "${TMP_DIR:?TMP_DIR not set}"
: "${APP_NAME:?APP_NAME not set}"
: "${DOMAIN_NAME:?DOMAIN_NAME not set}"
: "${FASTIFY_APP_PORT:?FASTIFY_APP_PORT not set}"
: "${FASTIFY_APP_DATA_PATH:?FASTIFY_APP_DATA_PATH not set}"
: "${PROJECT_DIR:?PROJECT_DIR not set}"
: "${SITE_ENV_FILE:?SITE_ENV_FILE not set — deploy/sites/<site>.conf must export it}"

DATA_DIR="${FASTIFY_APP_DATA_PATH}/${APP_NAME}"   # e.g. /var/www/rkr-blog

# SITE_ROOT lives in the site's env file ($SITE_ENV_FILE), not the shell
# environment — deploy.sh sources <site>.conf but never that file. It must
# name the same directory the systemd unit owns; a mismatch yields a service
# that starts and then cannot write — expensive to diagnose, cheap to catch
# here. Read as data (not sourced): the file may carry comments and other
# keys we must not execute.
site_env_path="$PROJECT_DIR/$SITE_ENV_FILE"
if [[ ! -f "$site_env_path" ]]; then
  echo "apache.build.post: $SITE_ENV_FILE does not exist" >&2
  exit 1
fi
site_root="$(grep -E '^SITE_ROOT=' "$site_env_path" 2>/dev/null | tail -n1 | cut -d= -f2- | sed -e 's/[[:space:]]*$//' || true)"
if [[ -z "$site_root" ]]; then
  echo "apache.build.post: $SITE_ENV_FILE has no SITE_ROOT= line — it must set SITE_ROOT" >&2
  exit 1
fi
if [[ "$site_root" != "$DATA_DIR" ]]; then
  echo "apache.build.post: SITE_ROOT ($site_root) in $SITE_ENV_FILE != ${FASTIFY_APP_DATA_PATH}/${APP_NAME} ($DATA_DIR)" >&2
  exit 1
fi

APP_DIR="${FASTIFY_APP_BASE_PATH:-/opt}/${APP_NAME}"  # e.g. /opt/rkr-blog
PORT="${FASTIFY_APP_PORT}"

# Optional extra hostnames served by this vhost. letsencrypt/start.sh reads the
# same variable to add SAN entries, so cert and vhost stay in agreement.
ALIASES="${APACHE_SERVER_ALIASES:-}"
ALIAS_LINE=""
REDIRECT_BLOCK=""
if [[ -n "$ALIASES" ]]; then
  for a in $ALIASES; do
    ALIAS_LINE+="    ServerAlias ${a}"$'\n'
  done
  # Escape dots for the regex-matched Host check.
  canonical_re="${DOMAIN_NAME//./\\.}"
  REDIRECT_BLOCK="    # Canonical host: send every alias to ${DOMAIN_NAME}.
    RewriteCond %{HTTP_HOST} !^${canonical_re}\$ [NC]
    RewriteRule ^(.*)\$ https://${DOMAIN_NAME}\$1 [R=301,L]
"
fi

cat > "${TMP_DIR}/${APP_NAME}.conf" << EOF
# Apache vhost for ${APP_NAME} — generated by deploy/hooks/apache.build.post.sh
# Required modules: rewrite proxy proxy_http headers

<VirtualHost *:80>
    ServerName ${DOMAIN_NAME}
${ALIAS_LINE}
    # Preserve ACME challenge directory for Let's Encrypt renewal
    Alias /.well-known ${DATA_DIR}/.well-known
    <Directory ${DATA_DIR}/.well-known>
        Require all granted
    </Directory>

    RewriteEngine On
    RewriteCond %{REQUEST_URI} !^/\.well-known
    RewriteRule ^(.*)$ https://%{HTTP_HOST}\$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName ${DOMAIN_NAME}
${ALIAS_LINE}
    SSLEngine on
    SSLCertificateFile    /etc/letsencrypt/live/${DOMAIN_NAME}/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/live/${DOMAIN_NAME}/privkey.pem

    ErrorLog  /var/log/apache2/${APP_NAME}_error.log
    CustomLog /var/log/apache2/${APP_NAME}_access.log combined

    # DocumentRoot is needed so %{DOCUMENT_ROOT} resolves in the RewriteCond
    # below.  The directory itself is never listed (Options -Indexes).
    DocumentRoot ${DATA_DIR}
    <Directory ${DATA_DIR}>
        Options -Indexes
        Require all granted
    </Directory>

    RewriteEngine On

${REDIRECT_BLOCK}
    # Fast-path: serve cached image derivatives directly from disk.
    # URI:  /img/<id>.<ophash>.<format>
    # Disk: ${DATA_DIR}/cache/img/<id>.<ophash>.<format>
    # Falls through to ProxyPass on cache miss.
    RewriteCond %{DOCUMENT_ROOT}/cache%{REQUEST_URI} -f
    RewriteRule ^/img/(.*)$ /cache/img/\$1 [L]

    # Standalone image-editor PWA (apps/image-pwa) — static files staged at
    # ${APP_DIR}/image-editor by fastify_app.build.post.sh. Served directly by
    # Apache (the '!' excludes it from the proxy below). Must precede ProxyPass /.
    Alias /image-editor ${APP_DIR}/image-editor
    <Directory ${APP_DIR}/image-editor>
        Options -Indexes
        Require all granted
    </Directory>
    ProxyPass /image-editor !

    ProxyPreserveHost On
    RequestHeader set X-Forwarded-Proto "https" env=HTTPS
    ProxyPass        / http://127.0.0.1:${PORT}/ enablereuse=on
    ProxyPassReverse / http://127.0.0.1:${PORT}/

    # Long-lived immutable cache for content-hashed URLs
    <LocationMatch "^/(cache|static)/">
        Header set Cache-Control "public, max-age=31536000, immutable"
    </LocationMatch>
</VirtualHost>
EOF

echo "  apache.build.post: custom rkr-blog vhost written"
