#!/usr/bin/env node
/**
 * Build the legal/about pages: markdown -> HTML.
 * Run with: node website/build-legal.js
 *
 * Sources: about.md / privacy.md / terms.md (edit these).
 * Output:  public/about.html / public/privacy.html / public/terms.html
 *          (generated; do not edit). Only public/ is deployed to the web
 *          root, so the markdown sources and this script stay private.
 *
 * Supported tokens in markdown:
 *   {{brand.name}}         -> rkr-blog
 *   {{brand.supportEmail}} -> mailto: link
 *   {{brand.websiteUrl}}   -> marketing site URL
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { marked } from 'marked';

const __dirname = dirname(fileURLToPath(import.meta.url));

marked.setOptions({ gfm: true, breaks: false });

const brand = {
  name: 'rkr-blog',
  supportEmail: 'john@rkroll.com',
  websiteUrl: 'https://rkr-blog-www.rkroll.com',
};

// Shared palette + prose styling, matching index.html (crimson on warm paper).
const styles = `
        :root {
            --accent: #cf222e;
            --accent-hover: #a40e26;
            --accent-soft: #fbeceb;
            --bg-page: #fdfdfb;
            --bg-card: #ffffff;
            --bg-soft: #ebeae4;
            --text-primary: #1f2328;
            --text-secondary: #5b6573;
            --text-muted: #8b939e;
            --border-color: #e2e1db;
            --nav-bg: #ffffff;
            --footer-bg: #1f2328;
            --footer-text: #b7bcc4;
        }
        body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif; background-color: var(--bg-page); color: var(--text-primary); }
        .prose h1 { font-size: 2rem; font-weight: 700; color: var(--text-primary); margin-bottom: 1rem; }
        .prose h2 { font-size: 1.4rem; font-weight: 700; color: var(--text-primary); margin-top: 2.25rem; margin-bottom: 0.75rem; }
        .prose h3 { font-size: 1.15rem; font-weight: 600; color: var(--text-primary); margin-top: 1.5rem; margin-bottom: 0.5rem; }
        .prose p { color: var(--text-secondary); margin-bottom: 1rem; line-height: 1.7; }
        .prose ul { list-style-type: disc; margin-left: 1.5rem; margin-bottom: 1rem; color: var(--text-secondary); }
        .prose li { margin-bottom: 0.25rem; }
        .prose a { color: var(--accent); text-decoration: underline; }
        .prose a:hover { color: var(--accent-hover); }
        .prose hr { border-color: var(--border-color); margin: 2rem 0; }
        .prose strong { font-weight: 600; color: var(--text-primary); }
        .prose em { font-style: italic; }
`;

function navLinks(current) {
  const links = [];
  if (current !== 'index.html') {
    links.push('<a href="index.html" class="hover:opacity-80" style="color: var(--text-secondary);">Home</a>');
  }
  if (current !== 'about.html') {
    links.push('<a href="about.html" class="hover:opacity-80" style="color: var(--text-secondary);">About</a>');
  }
  return links.join('\n                    ');
}

function footerLinks(current) {
  const pages = [
    ['index.html', 'Home'],
    ['about.html', 'About'],
    ['privacy.html', 'Privacy'],
    ['terms.html', 'Terms'],
  ];
  return pages
    .filter(([href]) => href !== current)
    .map(([href, label]) => `<a href="${href}" class="text-sm hover:text-white">${label}</a>`)
    .join('\n                    ');
}

function applyTokens(html) {
  return html
    .replace(/\{\{brand\.name\}\}/g, brand.name)
    .replace(/\{\{brand\.websiteUrl\}\}/g, `<a href="${brand.websiteUrl}">${brand.websiteUrl}</a>`)
    .replace(
      /\{\{brand\.supportEmail\}\}/g,
      `<a href="mailto:${brand.supportEmail}">${brand.supportEmail}</a>`,
    );
}

function generatePage(mdFile, htmlFile, title) {
  const mdContent = readFileSync(join(__dirname, mdFile), 'utf-8');
  const contentHtml = applyTokens(marked.parse(mdContent));

  const fullHtml = `<!--
================================================================================
    DO NOT EDIT THIS FILE DIRECTLY!
    Auto-generated by website/build-legal.js from website/${mdFile}.
    Edit the .md source and run: node website/build-legal.js
================================================================================
-->
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="${brand.name} — ${title}">
    <title>${title} — ${brand.name}</title>
    <link rel="icon" type="image/svg+xml" href="rkr-blog-icon.svg">
    <script src="https://cdn.tailwindcss.com"></script>
    <style>${styles}    </style>
</head>
<body>
    <!-- Navigation -->
    <nav class="shadow-sm sticky top-0 z-50" style="background-color: var(--nav-bg);">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex justify-between h-16 items-center">
                <a href="index.html" class="flex items-center gap-2">
                    <img src="rkr-blog-icon.svg" alt="${brand.name}" class="h-9">
                    <span class="text-xl font-bold" style="color: var(--text-primary);">${brand.name}</span>
                </a>
                <div class="flex items-center space-x-8">
                    ${navLinks(htmlFile)}
                </div>
            </div>
        </div>
    </nav>

    <!-- Content -->
    <div class="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div class="rounded-lg shadow-sm border p-8 md:p-12 prose" style="background-color: var(--bg-card); border-color: var(--border-color);">
            ${contentHtml}
        </div>
    </div>

    <!-- Footer -->
    <footer class="py-6" style="background-color: var(--footer-bg); color: var(--footer-text);">
        <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div class="flex items-center gap-4">
                <p class="text-sm">&copy; 2026 <a href="https://rkroll.com" class="hover:text-white">rkroll.com</a></p>
                    ${footerLinks(htmlFile)}
            </div>
        </div>
    </footer>
</body>
</html>
`;

  // Trim trailing whitespace per line + guarantee one final newline (eof gate).
  const clean = `${fullHtml
    .split('\n')
    .map((line) => line.replace(/\s+$/, ''))
    .join('\n')
    .replace(/\n+$/, '')}\n`;

  writeFileSync(join(__dirname, 'public', htmlFile), clean);
  console.log(`Generated public/${htmlFile} from ${mdFile}`);
}

generatePage('about.md', 'about.html', 'About');
generatePage('privacy.md', 'privacy.html', 'Privacy Policy');
generatePage('terms.md', 'terms.html', 'Terms of Service');

console.log('All legal pages generated.');
